name: house
description: "نظام إدارة الشقق السكنية للموبايل"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  excel: ^4.0.0
  file_picker: ^8.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # مكتبة تغيير الأيقونة
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة (ضع صورتك في مجلد assets باسم app_icon.png)

flutter:
  uses-material-design: true



